### ISSUE TITLE
 app.use() requires a generator function

### ISSUE THREAD

**Issue by LivesleyWA** [koa-modules/methodoverride#1]
(Typescript) Code is as follows:-

```
import * as KOA_METHOD_OVERRIDE from "koa-methodoverride";
...
this.server.use(KOA_METHOD_OVERRIDE());
```

koa 1.1.2

The code gets as far as _return (ctx, next) => {_ in the index.js file.

Is this something to do with the switch to Koa v2?

**Comment by haoxins** [comment]
@LivesleyWA  you need use koa-methodoverride@1 for koa@1

**Comment by LivesleyWA** [comment]
Thanks - I obvously started the work on an Express to Koa migration at the wrong time!
